### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by bihline** [DenBeke/ZeeJong#2]
hello,

I register and loged in as Admin but can't find admin panel where I can add matches, etc...
or in this script missing folder "admin"
Can you help me

Thanks a lot

**Comment by trtstm** [comment]
Tbh, this project is dead. It was for a university course we did 2 years ago.
So you shouldn't use it :).

**Comment by bihline** [comment]
ah. okay, thanks
I found it just searching php scripts on github

**Comment by trtstm** [comment]
Ok, we should probably takes this repo offline :p, since you are not the first who wants to use it :p.
Anyway goodluck finding an alternative.

**Comment by bihline** [comment]
No problem :D 
all the best
